name: CI
on: [push, pull_request]
jobs:
	flatpak:
		runs-on: ubuntu-latest
		container:
			image: ghcr.io/elementary/flatpak-platform/runtime:6
			options: --privileged
		- uses: actions/checkout@v2
		- uses: bilelmoussaoui/flatpak-github-actions/flatpak-builder@v3
			with:
				bundle: gtk-vala-hello_again.flatpak
				manifest-path: com.github.gabrielangelcabrera.vala_app.yml
				run-tests: true
				repository-name: appcenter
				repository-url: https://flatpak.elementary.io/repo.flatpakrepo
				cache-key: "flatpak-builder-${{github.sha}}"
		
